apiVersion: v1
kind: Service
metadata:
  namespace: k8s-book
  name: go-app-service
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      # tells Kubernetes to listen internally on that port
      port: 8081
      # tells Kubernetes where to route the traffic to that port of the pods
      targetPort: 8888
      # tells Kubernetes to expose the service on the specified nodePort
      nodePort: 30080
  type: NodePort
